spring:
  config:
    activate:
      on-profile: local

  application:
    name:
      hot-place

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  r2dbc:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
    pool:
      enabled: false
    properties:
      initialization-mode: always

logging.level.org.springframework:
  transaction: TRACE
  data.r2dbc: TRACE

---
spring:
  config:
    activate:
      on-profile: prd

  application:
    name:
      hot-place

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: { url }
    username: { username }
    password: { password }
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 3m
      max-create-connection-time: 3s
      max-life-time: 3m
      validation-query: SELECT 1
    properties:
      connect-timeout: 3s
      max-acquire-time: 3s

logging.level.org.springframework:
  transaction: INFO
  data.r2dbc: INFO
